### ISSUE TITLE
ofMutex has private copy constructor

### ISSUE THREAD

**Issue by theceremony** [tgfrerer/ofxPlaylist#3]
I get this error anytime I try to compile 0.8.4. Is there a fix?
https://github.com/openframeworks/openFrameworks/issues/2410

**Comment by tgfrerer** [comment]
Are you getting this error in ofxPlaylist or in openFrameworks or in a project you are working on?

**Comment by theceremony** [comment]
yes getting in my project when I include ofxPlaylist.h

**Comment by tgfrerer** [comment]
hmmm. difficult to tell without seeing some code. i'd say you're trying to deep-copy a playlist, and since the playlist has an ofMutex that's not going down well.

are you using a vector of ofxPlaylists? if so, try changing this to a vector of `shared_ptr<ofxPlaylist>` - that way, you are not deep-copying things. that said, it's often better to just have one ofxPlaylist around, and queue up keyframes within one playlist - this allows you to make sure things are synchronised within.

**Comment by theceremony** [comment]
Ah, that makes sense. Yeah I have a vector of animating objects that were using playlists.

Thanks!!
